version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5232:5432
    env_file: $BASE_PATH/services/postgres/.env.development
    volumes:
      - db_data:/var/lib/postgresql/data
  hasura:
    image: hasura/graphql-engine:v2.5.0
    restart: always
    ports:
      - 8080:8080
    build:
      context: $BASE_PATH/services/hasura  
    env_file: $BASE_PATH/services/hasura/.env.development
volumes:
  db_data:
