version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5232:5432
    env_file: $BASE_PATH/services/postgres/.env.production
    volumes:
      - db_data:/var/lib/postgresql/data

  hasura:
    image: $ECR_REGISTRY/birdeye-hasura:$IMAGE_TAG
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "postgres"  
    env_file: $BASE_PATH/services/hasura/.env.production

  caddy:
    image: $ECR_REGISTRY/birdeye-caddy:$IMAGE_TAG
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '2019:2019'
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db_data:
  caddy_config:
  caddy_data:
